export const councilMemberData = [
  {
    Name: "American Institute of Aeronautics and Astronautics",
    OrgAcronym: "AIAA",
    Links: ["http://aiaaucsd.com/", "ucsdaiaa"],
    Image: "AIAA.png",
  },
  {
    Name: "American Institute of Chemical Engineers",
    OrgAcronym: "AIChE",
    Links: ["https://www.aiche.ucsd.edu/", "aicheucsd"],
    Image: "AIChE.jpeg",
  },
  {
    Name: "Association for Computing Machinery",
    OrgAcronym: "ACM",
    Links: ["https://acmucsd.com", "acm.ucsd"],
    Image: "ACM.png",
  },
  {
    Name: "Biomedical Engineering Society",
    OrgAcronym: "BMES",
    Links: ["https://bmes.ucsd.edu/", "ucsd_bmes"],
    Image: "BMES.png",
  },
  {
    Name: "Chem-E-Car at UCSD",
    OrgAcronym: "CEC",
    Links: ["https://sites.google.com/a/ucsd.edu/chemecar", "chemecar_ucsd"],
    Image: "CEC.jpg",
  },
  {
    Name: "Chinese Engineering Society",
    OrgAcronym: "CES",
    Links: ["https://ucsdces.com", "ucsdces"],
    Image: "CES.jpeg",
  },
  {
    Name: "Computer Science & Engineering Society",
    OrgAcronym: "CSES",
    Links: ["https://csesucsd.com", "cses_ucsd"],
    Image: "CSES.png",
  },
  {
    Name: "CS foreach",
    OrgAcronym: "CSFE",
    Links: ["csforeach.org", "csforeach"],
    Image: "CSFE.png",
  },
  {
    Name: "Data Science Society",
    OrgAcronym: "DS3",
    Links: ["https://www.ds3ucsd.com", "ds3.ucsd"],
    Image: "DS3.png",
  },
  {
    Name: "Design/Build/Fly at UCSD",
    OrgAcronym: "DBF",
    Links: ["https://dbf.ucsd.edu", "ucsd_dbf"],
    Image: "DBF.png",
  },
  {
    Name: "ECE Undergraduate Student Council",
    OrgAcronym: "ECE USC",
    Links: ["eceusc.ucsd.edu", "eceusc_ucsd"],
    Image: "ECE-USC.png",
  },
  {
    Name: "Engineering World Health",
    OrgAcronym: "EWH",
    Links: ["ewh.ucsd.edu", "ewh.at.ucsd"],
    Image: "EWH.png",
  },
  {
    Name: "Engineers Without Borders at UCSD",
    OrgAcronym: "EWB",
    Links: ["https://linktr.ee/ewbucsandiego", "ewb_ucsandiego"],
    Image: "EWB.png",
  },
  {
    Name: "EnVisionaries",
    OrgAcronym: "EnV",
    Links: ["https://linktr.ee/Envisionaries", ""],
    Image: "EnV.png",
  },
  {
    Name: "Eta Kappa Nu",
    OrgAcronym: "HKN",
    Links: ["hkn.ucsd.edu", "hkn_ucsd"],
    Image: "HKN.png",
  },
  {
    Name: "Gender Minorities in Bioengineering",
    OrgAcronym: "GMBE",
    Links: ["gmbe.ucsd.edu", "gmbe.ucsd"],
    Image: "GMBE.jpeg",
  },
  {
    Name: "Human Powered Submarine at UC San Diego",
    OrgAcronym: "HPS",
    Links: ["https://hps-ucsd-2020.github.io/Home.html", "hps_ucsandiego"],
    Image: "HPS.jpeg",
  },
  {
    Name: "Institute of Electrical and Electronics Engineers",
    OrgAcronym: "IEEE",
    Links: ["https://ieeeucsd.org/", "ieee.ucsd"],
    Image: "IEEE.png",
  },
  {
    Name: "International Society for Pharmaceutical Engineering",
    OrgAcronym: "ISPE",
    Links: ["https://ispeucsd.weebly.com/", "ispeucsd"],
    Image: "ISPE.png",
  },
  {
    Name: "KK6UC Amateur Radio Club at UC San Diego",
    OrgAcronym: "KK6UC",
    Links: ["https://kk6uc.ucsd.edu/", "kk6uc"],
    Image: "KK6UC.jpeg",
  },
  {
    Name: "NanoEngineering & Technology Society",
    OrgAcronym: "NETS",
    Links: ["https://netsucsd.weebly.com/", "netsucsd"],
    Image: "NETS.png",
  },
  {
    Name: "National Society of Black Engineers\nat UC San Diego",
    OrgAcronym: "NSBE",
    Links: ["https://nsbe.ucsd.edu/", "nsbeucsd"],
    Image: "NSBE.png",
  },
  {
    Name: "out in Science, Technology, Engineering and Mathematics",
    OrgAcronym: "oSTEM",
    Links: ["https://ostem.ucsd.edu/", "ostemucsd"],
    Image: "oSTEM.png",
  },
  {
    Name: "Project in a Box",
    OrgAcronym: "PiB",
    Links: ["https://pib.ucsd.edu/", "pibucsd"],
    Image: "PiB.png",
  },
  {
    Name: "Rocket Propulsion Laboratory",
    OrgAcronym: "RPL",
    Links: ["https://www.rocketproplab.org/", "rpl.ucsd"],
    Image: "RPL.png",
  },
  {
    Name: "Society of Asian Scientists and Engineers",
    OrgAcronym: "SASE",
    Links: ["https://saseatucsd.weebly.com/about-us.html", "saseucsd"],
    Image: "SASE.png",
  },
  {
    Name: "Society of Automotive Engineers at UC San Diego",
    OrgAcronym: "SAE",
    Links: ["sae.eng.ucsd.edu", "tritonracing"],
    Image: "SAE.png",
  },
  {
    Name: "Society of Civil and Structural Engineers",
    OrgAcronym: "SCSE",
    Links: ["https://scse.ucsd.edu/home.html", "scse.ucsd"],
    Image: "SCSE.png",
  },
  {
    Name: "Society of Hispanic Professional Engineers at UC San Diego",
    OrgAcronym: "SHPE",
    Links: ["https://sites.google.com/view/shpeucsd/home", "shpeatucsd"],
    Image: "SHPE.png",
  },
  {
    Name: "Society of Women Engineers",
    OrgAcronym: "SWE",
    Links: ["https://swe-ucsd.netlify.app/", "swe.ucsd"],
    Image: "SWE.png",
  },
  {
    Name: "Student Foundation Investment Committee UCSD",
    OrgAcronym: "SFIC",
    Links: ["https://ucsdsfic.weebly.com/about.html", "sfic_ucsd"],
    Image: "SFIC.jpeg",
  },
  {
    Name: "Students for the Exploration and Development of Space",
    OrgAcronym: "SEDS",
    Links: ["https://www.sedsucsd.org/", "seds_ucsd"],
    Image: "SEDS.jpeg",
  },
  {
    Name: "Tau Beta Pi",
    OrgAcronym: "TBP",
    Links: ["https://tbp.ucsd.edu/home", "tbpucsd"],
    Image: "TBP.png",
  },
  {
    Name: "Triangle",
    OrgAcronym: "Triangle",
    Links: ["https://linktr.ee/UCSDTriangle", "triangle_ucsd"],
    Image: "Triangle.png",
  },
  {
    Name: "Triton AI",
    OrgAcronym: "Triton AI",
    Links: ["https://triton-ai.info/", "triton.ai"],
    Image: "Triton-AI.jpeg",
  },
  {
    Name: "Triton BAJA",
    OrgAcronym: "Triton BAJA",
    Links: ["https://sites.google.com/ucsd.edu/tritonbaja", "tritonbaja"],
    Image: "Triton-BAJA.png",
  },
  {
    Name: "Triton Droids",
    OrgAcronym: "Triton Droids",
    Links: ["https://www.tritondroids.com/", "tritondroids"],
    Image: "Triton-Droids.jpeg",
  },
  {
    Name: "Triton NeuroTech",
    OrgAcronym: "TNT",
    Links: ["https://neurotech.ucsd.edu/", "tntucsd"],
    Image: "TNT.jpeg",
  },
  {
    Name: "Triton Quantitative Trading",
    OrgAcronym: "TQT",
    Links: ["https://tquantt.ucsd.edu/", "tqt_ucsd"],
    Image: "TQT.jpeg",
  },
  {
    Name: "Triton Racing",
    OrgAcronym: "Triton Racing",
    Links: ["sae.eng.ucsd.edu", "tritonracing"],
    Image: "Triton-Racing.png",
  },
  {
    Name: "Triton Robosub",
    OrgAcronym: "RBSB",
    Links: ["https://robosub.ucsd.edu", "tritonrobosub"],
    Image: "RBSB.png",
  },
  {
    Name: "Triton Robotics",
    OrgAcronym: "TR",
    Links: ["https://tritonrobotics.ucsd.edu", "tritonrobotics"],
    Image: "TR.png",
  },
  {
    Name: "Triton Software Engineering",
    OrgAcronym: "TSE",
    Links: ["https://tse.ucsd.edu/", "ucsd_tse"],
    Image: "TSE.png",
  },
  {
    Name: "Triton Solar Car",
    OrgAcronym: "TSC",
    Links: ["https://ucsdsolarcar.org/", "ucsdsolarcar/"],
    Image: "TSC.png",
  },
  {
    Name: "Triton Unmanned Aerial Systems",
    OrgAcronym: "TUAS",
    Links: ["https://tuas.ucsd.edu/", ""],
    Image: "TUAS.png",
  },
  {
    Name: "Vertical Flight Society @ UC San Diego",
    OrgAcronym: "VFS",
    Links: ["", "vfs.ucsd"],
    Image: "VFS.jpeg",
  },
  {
    Name: "Women in Computing",
    OrgAcronym: "WIC",
    Links: ["https://wic.ucsd.edu/", "wicucsd"],
    Image: "WIC.jpeg",
  },
  {
    Name: "Yonder Deep",
    OrgAcronym: "Yonder Deep",
    Links: ["https://yonderdeep.ucsd.edu/", "yonderdeep"],
    Image: "Yonder-Deep.jpeg",
  },
  {
    Name: "Yonder Dynamics",
    OrgAcronym: "YNDR",
    Links: ["https://yonderdynamics.org/", "yonderdynamics"],
    Image: "YNDR.jpeg",
  },
];
