export const pvpData: string[][] = [
  [
    "Jasper Huang",
    "Co-President",
    "Computer Engineering",
    "/member-pictures/Jasper-Huang.jpg",
    "https://www.linkedin.com/in/yj-huang/",
    "jasper@tesc.ucsd.edu",
  ],
  [
    "Shree Venkatesh",
    "Co-President",
    "Computer Science",
    "/member-pictures/Shree-Venkatesh.jpg",
    "https://www.linkedin.com/in/shree-venkatesh/",
    "shree@tesc.ucsd.edu",
  ],
  [
    "Ashley Choi",
    "VP External",
    "Political Science",
    "/member-pictures/Ashley-Choi.jpg",
    "",
    "ashley@tesc.ucsd.edu",
  ],
  [
    "Chloe Pracharktam",
    "VP Events",
    "Chemical Engineering",
    "/member-pictures/Chloe-Pracharktam.jpg",
    "",
    "ashley@tesc.ucsd.edu",
  ],
  [
    "Rohan Sachdeva",
    "VP Internal",
    "Computer Science",
    "/member-pictures/Rohan-Sachdeva.jpg",
    "https://www.linkedin.com/in/rohanvsachdeva/",
    "rohan@tesc.ucsd.edu",
  ],
  [
    "Pearl Wen",
    "VP Finance",
    "Cognitive Science",
    "/member-pictures/Pearl-Wen.jpg",
    "https://www.linkedin.com/in/pearl-wen-3a66a8263",
    "pearl@tesc.ucsd.edu",
  ],
  [
    "Christine Nguyen",
    "Former VP External",
    "Computer Science",
    "/member-pictures/Christine-Nguyen.jpg",
    "https://www.linkedin.com/in/christine-nguyen-79538a1b8",
    "christine@tesc.ucsd.edu",
  ],
];

export const committeeLeadsData: string[][] = [
  [
    "Anika Agarwal",
    "Social Lead",
    "Computer Engineering",
    "/member-pictures/Anika-Agarwal.jpg",
    "",
    "anika_agarwal@tesc.ucsd.edu",
  ],
  [
    "Melchisedec Lai",
    "Sponsorship Lead",
    "Nanoengineering",
    "/member-pictures/Mel-Lai.jpg",
    "https://www.linkedin.com/in/mel-lai/",
    "melchisedec@tesc.ucsd.edu",
  ],
  [
    "Julia Nguyen",
    "Financial Analyst",
    "Business Economics",
    "/member-pictures/Julia-Nguyen.jpg",
    "",
    "julia@tesc.ucsd.edu",
  ],
  [
    "Nishitha Selvakumar",
    "Tech Lead",
    "Computer Science",
    "/member-pictures/Nishitha-Selvakumar.jpg",
    "",
    "nishitha@tesc.ucsd.edu",
  ],
  [
    "Jonathan Ty",
    "Design Lead",
    "Computer Science",
    "/member-pictures/Jonathan-Ty.png",
    "",
    "ty@tesc.ucsd.edu",
  ],
  [
    "Kai Velasco",
    "Operations Lead",
    "Structural Engineering",
    "/member-pictures/Profile_avatar_placeholder_large.png",
    "",
    "kai@tesc.ucsd.edu",
  ],
];

export const social: string[][] = [
  [
    "Elizabeth Dam",
    "Social",
    "Electrical Engineering",
    "/member-pictures/Elizabeth-Dam.jpg",
    "",
    "elizabeth@tesc.ucsd.edu",
  ],
];
export const tech: string[][] = [
  [
    "Ferrari Guan",
    "Tech",
    "Computer Engineering",
    "/member-pictures/Ferrari-Guan.jpg",
    "",
    "ferrari@tesc.ucsd.edu",
  ],
  [
    "Nabhya Gupta",
    "Tech",
    "Computer Engineering",
    "/member-pictures/Nabhya-Gupta.jpg",
    "",
    "nabhya@tesc.ucsd.edu",
  ],
  [
    "Hieu Nguyen",
    "Tech",
    "Mathematics-Computer Science",
    "/member-pictures/Hieu-Nguyen.jpg",
    "",
    "hieu.nguyen@tesc.ucsd.edu",
  ],
  [
    "Thanh Trinh",
    "Tech",
    "Computer Engineering",
    "/member-pictures/Thanh-Trinh.jpg",
    "https://www.linkedin.com/in/thanh-trinh-329373245/",
    "thanh@tesc.ucsd.edu",
  ],
];
export const design: string[][] = [
  [
    "Mia Jin",
    "Design",
    "Cognitive Science",
    "/member-pictures/Mia-Jin.jpg",
    "",
    "mia@tesc.ucsd.edu",
  ],
  [
    "Anna Pham",
    "Design",
    "Chemical Engineering",
    "/member-pictures/Anna-Pham.jpeg",
    "",
    "anna@tesc.ucsd.edu",
  ],
  [
    "Jenna Vo",
    "Design",
    "Aerospace Engineering",
    "/member-pictures/Jenna-Vo.jpeg",
    "",
    "jenna@tesc.ucsd.edu",
  ],
];
export const marketing: string[][] = [
  [
    "Shruti Senthilram",
    "Marketing",
    "Computer Science",
    "/member-pictures/Shruti-Senthilram.jpg",
    "",
    "shruti@tesc.ucsd.edu",
  ],
];
export const operations: string[][] = [
  [
    "Eden Mai",
    "Operations",
    "Aerospace Engineering",
    "/member-pictures/Eden-Mai.png",
    "",
    "edenm@tesc.ucsd.edu",
  ],
  [
    "Arnav Sahu",
    "Operations",
    "Electrical Engineering",
    "/member-pictures/Arnav-Sahu.jpg",
    "",
    "arnav@tesc.ucsd.edu",
  ],
  [
    "Ashton Simbol",
    "Operations",
    "Computer Science",
    "/member-pictures/Ashton-Simbol.jpg",
    "",
    "ashton@tesc.ucsd.edu",
  ],
  [
    "Kevin Yang",
    "Operations",
    "Computer Science",
    "/member-pictures/Kevin-Yang.jpg",
    "",
    "kevin@tesc.ucsd.edu",
  ],
];
export const sponsorship: string[][] = [
  [
    "Rachel Mao",
    "Sponsorship",
    "Structural Engineering",
    "/member-pictures/Rachel-Mao.jpg",
    "",
    "rachel@tesc.ucsd.edu",
  ],
  [
    "Kavya Shah",
    "Sponsorship",
    "Mathematics-Computer Science",
    "/member-pictures/Kavya-Shah.jpg",
    "",
    "kavya@tesc.ucsd.edu",
  ],
];
export const prodev: string[][] = [
  [
    "Aditya Sivanandan",
    "ProDev",
    "Mechanical Engineering",
    "/member-pictures/Aditya-Sivanandan.jpg",
    "",
    "aditya@tesc.ucsd.edu",
  ],
  [
    "Brooke Truong",
    "ProDev",
    "Computer Science",
    "/member-pictures/Brooke-Truong.jpg",
    "",
    "brooke@tesc.ucsd.edu",
  ],
];
